services:
  website:
    image: brunoir/www.ignaz.dev:latest
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./dist:/www:ro # enables automatic reloads for development
    networks:
      - proxynet
    ports:
      - 80:80

networks:
  proxynet:
    #external: true
